### ISSUE TITLE
Unable to view encoder stats - "1:87: parse error: unexpected number \"0\""

### ISSUE THREAD

**Issue by Strykar** [utkuozdemir/nvidia_gpu_exporter#42] opened 2021-10-09 19:45 UTC
**Describe the bug**
Trying to view encoder stats in a gauge [as suggested](https://github.com/utkuozdemir/nvidia_gpu_exporter/blob/master/METRICS.md) logs `"1:87: parse error: unexpected number \"0\""`.

**To Reproduce**
Add a panel with queries (replacing `$gpu` with the actual uuid does not work either):
```
nvidia_smi_encoder_stats_average_fps{uuid="$gpu"} 0
nvidia_smi_encoder_stats_average_latency{uuid="$gpu"} 0
nvidia_smi_encoder_stats_session_count{uuid="$gpu"} 0
```

2. See error
`1:87: parse error: unexpected number \"0\`

**Expected behavior**
To see 3 guages with encoder stats

**Model and Version**
 - GTX 950 and Quadro P400
 - `v0.3.0 - linux_x86_64`
 - Installed via binary download
 - Arch Linux
 -  `nvidia-driver-470.74`

**Comment by utkuozdemir** [comment] 2021-10-09 21:22
I have just tried it and it works fine:
![image](https://user-images.githubusercontent.com/1465819/136674031-3ee4967f-a5e2-4f12-a715-b126227866ee.png)

Zero (0) is a valid value in the exported metrics - so there is no problem with the metric `nvidia_smi_encoder_stats_average_fps{uuid="$gpu"} 0`. If there was, exporter would crash anyway.

I think the issue might be related to your Grafana version or its Prometheus plugin version (which is built-in, so goes together with Grafana version). Can you check that?

See the lines `"pluginVersion": "8.0.3"` in the dashboard.json: https://github.com/utkuozdemir/nvidia_gpu_exporter/blob/master/grafana/dashboard.json#L116

This means the dashboard is not guaranteed to run on any Grafana version <8.0.3.
Can you verify that?

**Comment by Strykar** [comment] 2021-10-10 03:55
I am trying this on Grafana's own hosted cloud, I can only assume they're running the latest version, but I'm unsure how to check.
Prometheus is v2.30.3. I assume the rest of the grafana settings are at defaults?

FWIW, the rest of the default metrics show up fine, why would this particular metric be affected by version?
![grafana_error](https://user-images.githubusercontent.com/2946372/136681206-bb7c6497-c95e-44aa-99ee-847f64f89486.png)

**Comment by Strykar** [comment] 2021-10-10 20:38
I see what you mean, `nvidia-smi encodersessions -l` won't show any value besides `0`.
However:
```
$ nvidia-smi dmon -s u
# gpu    sm   mem   enc   dec
# Idx     %     %     %     %
    0     4     7     8     3
    1     0     0     0     0
    0    25    17    10     3
    1     0     0     0     0
    0     3     7     7     2
    1     0     0     0     0
    0     3     7     5     2
    1     0     0     0     0
    0     3     7     7     2
    1     0     0     0     0
    0     5     8     5     2
    1     0     0     0     0
```

**Comment by Strykar** [comment] 2021-10-12 10:28
@utkuozdemir I found some more weirdness while testing with different cards.

So, a _GTX 1070_ and a _Quadro P4000_ (Pascal | GP104 | 6th Gen) will report encoder stats as expected via `nvidia-smi --query-gpu=encoder.stats`
OTOH, a _GTX 950_ and _Quadro P400_ (Pascal | GP107 | 6th Gen) will not, except, via `dmon`.

Unsure how much this helps, but it sheds some light on why `nvidia-smi --query-gpu=encoder.stats` may appear to work on some cards.

**Comment by utkuozdemir** [comment] 2021-10-19 15:22
@Strykar I see. I agree that it's weird - not sure if it's a bug in nvidia-smi or if it's the expected behavior.

In any case, the issue seems to be out of scope for this project, since all this exporter does is to expose what is returned by nvidia-smi. Therefore I am closing the issue.

If you have any findings that indicate and issue on this exporter, feel free to open a new issue.

**Closed as completed by utkuozdemir** 2021-10-19 15:22 UTC
