### ISSUE TITLE
relabel fail

### ISSUE THREAD

**Issue by happinesslijian** [utkuozdemir/nvidia_gpu_exporter#97] opened 2023-01-06 09:46 UTC
**Problem Description：**
Before relabeling, the instance I got was like this: 192.168.1.1:9835 which contains port :9835. Whenever an alarm is triggered, it carries: 9835 port information, because it is not very beautiful, so I try to use relabel. After I relabel, I found that all the original instances will not be overwritten, which leads to the pre-relabel and The data after relabel coexists! This is a very serious bug. I don't know if something was missed during the development of nvidia_gpu_exporter, so I submitted an issue. I tried to do the same with the officially maintained node_exporter, and found that after relabeling, the data before relabeling would be replaced. The two will not coexist. Below is my relabel configuration file:
```
relabel_configs:
   - action: replace
     source_labels: [__address__]
     regex: (.*):(.*)
     replacement: $1
     target_label: instance
```

**Comment by utkuozdemir** [comment] 2023-02-15 10:26
Hi, relabeling logic has nothing to do with the exporters. Exporters only expose metrics in a dummy way. Relabeling is done by the Prometheus itself. So the issue is probably your relabeling config is wrong.

Please double-check your config and try different combinations.

Since it is not related to the exporter in any way, I am closing the issue.

**Closed by utkuozdemir** 2023-02-15 10:26 UTC
